language: node_js
node_js:
    - 10
jobs:
    include:
        - stage: Install dependencies
          script: yarn install
        - stage: Build project & Tests
          script:
              - yarn build
              - yarn test
        - stage: build & publish docker image for server
          if: branch = master AND NOT type IN (pull_request)
          script:
              - yarn build
              - echo "Building docker image"
              - docker build -f docker/Dockerfile -t hltech/judge-d-ui:latest .
              - echo "Pushing to docker registry"
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker push hltech/judge-d-ui
              - echo "Pushing to heroku"
              - docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
              - docker tag hltech/judge-d-ui registry.heroku.com/judge-d-ui/web
              - docker push registry.heroku.com/judge-d-ui/web
        - stage: release app in heroku
          if: branch = master AND NOT type IN (pull_request)
          script:
              - heroku container:release web -a judge-d-ui
